practice/urls.py
from django.contrib import admin
from django.urls import path, include

from skolkovo.views import index, grants, services, quick_logout, navigator, my_companies, create_company, \
    create_product, delete_company, delete_product

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('grants/', grants, name='grants'),
    path('services/', services, name='services'),
    path('navigator/', navigator, name='navigator'),
    path('navigator/my_companies/', my_companies, name='my_companies'),
    path('navigator/my_companies/create', create_company),
    path('navigator/my_companies/<int:company_id>/create_product', create_product),
    path('navigator/my_companies/<int:company_id>/delete', delete_company),
    path('navigator/my_companies/delete_product/<int:product_id>', delete_product),

    path('accounts/', include('allauth.urls')),
    path('logout/', quick_logout, name='logout'),
]

skolkovo/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


class Company(models.Model):
    owner = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    creation_date = models.DateField()
    inn = models.CharField(max_length=10)


class Product(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    price = models.FloatField()

skolkovo/forms.py
from django import forms
from django.utils import timezone


def get_today_string():
    return timezone.localtime(timezone.now()).strftime('%d.%m.%Y')


class CompanyForm(forms.Form):
    name = forms.CharField(
        label='Название',
        max_length=200,
        required=True
    )
    inn = forms.CharField(
        label='ИНН',
        max_length=10,
        min_length=10,
        required=True
    )
    creation_date = forms.DateField(
        label='Дата создания',
        input_formats=('%Y-%m-%d',),
        widget=forms.TextInput(attrs={'type': 'date'}),
        initial=get_today_string,
        required=True
    )


class ProductForm(forms.Form):
    name = forms.CharField(
        label='Название',
        max_length=200,
        required=True
    )
    description = forms.CharField(
        label='Описание',
        max_length=2000,
        required=True
    )
    price = forms.FloatField(
        label='Цена',
        min_value=0,
        step_size=0.1
    )

skolkovo/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render

from skolkovo.forms import CompanyForm, ProductForm
from skolkovo.models import Company, Product


# Create your views here.
def index(request):
    return render(request, 'index.html', {})


def grants(request):
    return render(request, 'grants.html', {})


def services(request):
    return render(request, 'services.html', {})


def navigator(request):
    companies = Company.objects.all()
    return render(request, 'navigator.html', {'companies': companies})


# Показываем список компаний и продуктов пользователя, он должен быть залогинен
@login_required
def my_companies(request):
    companies = Company.objects.filter(owner=request.user)
    context = {'company_form': CompanyForm(),
               'product_form': ProductForm(),
               'companies': companies
               }
    return render(request, 'my_companies.html', context)


# Обработка формы создания новой компании, автоматически проверяем, что пользователь залогинен
@login_required
def create_company(request):
    # Проверяем корректность вида запроса
    if request.method == 'POST':
        form = CompanyForm(request.POST)
        # Средствами Django валидируем данные формы
        if form.is_valid():
            company = Company(owner=request.user, # Владелец компании по умолчанию залогиненный пользователь
                              name=form.cleaned_data['name'],
                              creation_date=form.cleaned_data['creation_date'],
                              inn=form.cleaned_data['inn'],
                              )
            company.save()
    # Обновляем пользователю страницу
    return HttpResponseRedirect('/navigator/my_companies/')


# Обработка формы создания нового продукта
@login_required
def create_product(request, company_id=0):
    if request.method == 'POST':
        try:
            company = Company.objects.get(id=company_id)
            # Проверяем, что продукт создается пользователем для своей, а не чужой компании
            if company.owner != request.user:
                return HttpResponseRedirect('/navigator/my_companies/')
        except ObjectDoesNotExist:
            return HttpResponseRedirect('/navigator/my_companies/')
        form = ProductForm(request.POST)
        if form.is_valid():
            product = Product(company=company,
                              name=form.cleaned_data['name'],
                              description=form.cleaned_data['description'],
                              price=form.cleaned_data['price'],
                              )
            product.save()
    return HttpResponseRedirect('/navigator/my_companies/')


@login_required
def delete_company(request, company_id=0):
    try:
        company = Company.objects.get(id=company_id)
        # Проверяем, что пользователь пытается удалить свою компанию
        if company.owner != request.user:
            return HttpResponseRedirect('/navigator/my_companies/')
        company.delete()
        return HttpResponseRedirect('/navigator/my_companies/')
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/navigator/my_companies/')


@login_required
def delete_product(request, product_id=0):
    try:
        product = Product.objects.get(id=product_id)
        # Проверяем, что пользователь пытается удалить продукт своей компании
        if product.company.owner != request.user:
            return HttpResponseRedirect('/navigator/my_companies/')
        product.delete()
        return HttpResponseRedirect('/navigator/my_companies/')
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/navigator/my_companies/')


# Выходим из аккаунта
def quick_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

skolkovo/views/index.py
from django.shortcuts import render

skolkovo/templates/grants.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Финансовая поддержка</h1>
    <div class='card-container'>
        <div class='block product'>
            <span class='title'>Внедрение искусственного интеллекта</span>
            <p>Гранты от 20 млн до 100 млн рублей на реализацию пилотных проектов апробации технологий искусственного интеллекта в приоритетных отраслях</p>
        </div>
        <div class='block product'>
            <span class='title'>Внедрение цифровых технологий</span>
            <p>Гранты от 20 млн до 700 млн рублей на реализацию особо значимых проектов пилотного внедрения российских решений в сфере информационных технологий</p>
        </div>
        <div class='block product'>
            <span class='title'>Создание дизайн-центров микроэлектроники</span>
            <p>Программа поддержки средних и малых дизайн-центров микроэлектроники, реализующих НИОКР в приоритетных направлениях развития электронной промышленности России</p>
        </div>
        <div class='block product'>
            <span class='title'>Инвестиции бизнес-ангелов</span>
            <p>Возмещение инвестиций физических лиц в участников проекта «Сколково»</p>
        </div>
        <div class='block product'>
            <span class='title'>Инвестиции в университетские стартапы</span>
            <p>Возмещение инвестиций в университетские стартапы в рамках федпроекта «Платформа университетского технологического предпринимательства»</p>
        </div>
        <div class='block product'>
            <span class='title'>Микрогранты</span>
            <p>Программа поддержки исследовательской деятельности, разработки и коммерциализации продуктов участников проекта «Сколково»</p>
        </div>
    </div>
{% endblock %}

skolkovo/templates/index.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
    <div class='welcome'>
        <img src={% static '/images/technopark.jpg' %}>
        <div class="news">
            <div class="date">
                <span>6 июня 2024</span>
            </div>
            <p>"Сколково", Минобрнауки и "Национальные приоритеты" объединяют усилия для развития техпредпринимательства</p>
            <div class="date">
                <span>6 июня 2024</span>
            </div>
            <p>"Сколково" и ДОМ.РФ займутся развитием искусственного интеллекта для строительной отрасли</p>
            <div class="date">
                <span>5 июня 2024</span>
            </div>
            <p>"Сколково" планирует поиск инновационных решений для wellness-индустрии</p>
            <div class="date">
                <span>4 июня 2024</span>
            </div>
            <p>Инструменты и сервисы поддержки для стартапов будет подбирать искусственный интеллект</p>
        </div>
    </div>

    <div class='card-container'>
        <div class='block grants'>
            <span class='title'>Гранты</span>
            <ul>
                <li>Внедрение искусственного интеллекта</li>
                <li>Внедрение цифровых технологий</li>
                <li>Создание дизайн-центров микроэлектроники</li>
                <li>Инвестиции бизнес-ангелов</li>
                <li>Инвестиции в университетские стартапы</li>
                <li>Микрогранты</li>
            </ul>
            <button onclick='window.location.assign("/grants");'>Узнать больше</button>
        </div>
        <div class='block services'>
            <span class='title'>Сервисы</span>
            <ul>
                <li>Таможенное декларирование</li>
                <li>Менторская программа</li>
                <li>Школа стартапов Skolkovo</li>
                <li>Экспертиза проектов</li>
                <li>Зарубежные бизнес-миссии</li>
                <li>Патентование в РФ и за рубежом</li>
            </ul>
            <button onclick='window.location.assign("/services");'>Узнать больше</button>
        </div>
    </div>
{% endblock %}

skolkovo/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="{% static '/images/favicon.ico' %}" type="image/x-icon">
        <script src="{% static '/javascript/display.js' %}"></script>
        <title>Сколково</title>
        <link rel='stylesheet' href="{% static '/css/style.css' %}">
        <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class='header'>
            <div class='menu'>
                <img src="{% static '/images/logo.png' %}" style='height: 4em;' onclick='window.location.assign("/");'>
                <a href='/navigator'>Участники</a>
                <a href='/grants'>Гранты</a>
                <a href='/services'>Сервисы</a>
            </div>
            <div class='short-menu'>
                <span class='short-title' onclick='toggleMenu();'>РАЗДЕЛЫ</span>
                <div id='short-menu-items' class='short-menu-items' style='display: none;'>
                    <span class='short-item' onclick='window.location.assign("/");'>Главная</span>
                    <span class='short-item' onclick='window.location.assign("/navigator");'>Участники</span>
                    <span class='short-item' onclick='window.location.assign("/grants");'>Гранты</span>
                    <span class='short-item' onclick='window.location.assign("/services");'>Сервисы</span>
                </div>
            </div>
            <div class='user'>
                {% if user.is_authenticated %}
                    <a href='/navigator/my_companies'>{{ user.username }}</a>
                    <a href='/logout'>выйти</a>
                {% else %}
                    <a href='/accounts/login'>войти</a>
                {% endif %}
            </div>
        </div>
        <div class='content'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

skolkovo/templates/my_companies.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <h1>Зарегистрировать компанию</h1>
        <form action='/navigator/my_companies/create' method='post' class="inline-form">
            {% csrf_token %}
            {{ company_form }}
            <button type='submit'>Зарегистрировать</button>
        </form>
    </div>
    {% for company in companies %}
        <div class='block company'>
            <span class='title'>{{ company.name }}</span>
            <br>
            <a href='/navigator/my_companies/{{ company.id|stringformat:"d" }}/delete'>удалить компанию</a>
            <br>
            <div class='card-container'>
                {% for product in company.product_set.all %}
                    <div class='block product'>
                        <span class='title'>{{ product.name }}</span>
                        <a href='/navigator/my_companies/delete_product/{{ product.id|stringformat:"d" }}'>удалить продукт</a>
                    </div>
                {% endfor %}
            </div>
            <h3>Добавить продукт</h3>
            <form action='/navigator/my_companies/{{ company.id|stringformat:"d" }}/create_product' method='post' class="inline-form">
                {% csrf_token %}
                {{ product_form }}
                <button type='submit'>Добавить</button>
            </form>
        </div>
    {% endfor %}
{% endblock %}

skolkovo/templates/navigator.html
{% extends 'layout.html' %}

{% block content %}
    {% for company in companies %}
        <div class='block company'>
            <span class='title'>{{ company.name }}</span>
            <p>Дата основания: {{ company.creation_date|date:'d.m.Y' }}</p>
            <p>ИНН: {{ company.inn }}</p>
            <div class='card-container'>
                {% for product in company.product_set.all %}
                    <div class='block product'>
                        <span class='title'>{{ product.name }}</span>
                        <span>{{ product.description }}</span>
                        <span>Цена: {{ product.price }} руб.</span>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

skolkovo/templates/services.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Сервисы Сколково</h1>
    <div class='card-container'>
        <div class='block product'>
            <span class='title'>Таможенное декларирование</span>
            <p>Таможенное декларирование, в том числе с возможностью   оплаты ввозной таможенной пошлины и НДС из средств субсидий</p>
        </div>
        <div class='block product'>
            <span class='title'>Менторская программа</span>
            <p>Услуга резидентам Фонда «Сколково» в поиске ментора и взаимодействии с ним. Мы поможем Вам найти подходящего наставника из перечня менторов Фонда «Сколково» и назначить с ним встречу.</p>
        </div>
        <div class='block product'>
            <span class='title'>Школа стартапов Skolkovo</span>
            <p>Школа стартапов – акселератор для стартапов стадии pre-seed, seed.</p>
        </div>
        <div class='block product'>
            <span class='title'>Экспертиза проектов</span>
            <p>Сервис научно-технологической и бизнес экспертизы любых, в том числе инновационных, проектов, с целью получения независимой оценки и поддержки принятия финансовых и инвестиционных решений.</p>
        </div>
        <div class='block product'>
            <span class='title'>Зарубежные бизнес-миссии</span>
            <p>Организация отраслевых B2B и B2G встреч с потенциальными партнёрами в рамках международного мероприятия или выезда в целевую страну.</p>
        </div>
        <div class='block product'>
            <span class='title'>Патентование в РФ и за рубежом</span>
            <p>Патентование ваших разработок в России и за рубежом обеспечивает защиту технологии и эксклюзивные права на ключевых рынках сбыта, увеличивает стоимость нематериальных активов и капитализацию вашей компании, подтверждает мировую новизну и уникальность разработки, пресекает незаконную конкуренцию.</p>
        </div>
    </div>
{% endblock %}